version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysqldummytestdb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'hunter2'
    ports:
      - '3329:3306'
    expose:
      - '3329'
    volumes:
      - './data:/var/lib/mysql'