version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "sergiuciudin"
    labels:
      - "dependencies"
    commit-message:
      prefix: "[NS-000] - "
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "sunday"
