version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
        - "major"
    reviewers:
      - "sergiuciudin"
    labels:
      - "dependencies"
    commit-message:
      prefix: "[NS-000] - (github-actions) "
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
